# Generated by Django 5.0.4 on 2024-06-12 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doubtResolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=100)),
                ('url1', models.URLField(null=True)),
                ('answer1', models.TextField(null=True)),
                ('url2', models.URLField(null=True)),
                ('answer2', models.TextField(null=True)),
                ('url3', models.URLField(null=True)),
                ('answer3', models.TextField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('rating', models.FloatField(null=True)),
                ('summary', models.TextField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pricecomparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100, null=True)),
                ('productlink', models.URLField(null=True)),
                ('price', models.FloatField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_searched_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weather_search_id', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('date1', models.DateField(null=True)),
                ('temp1', models.FloatField(null=True)),
                ('date2', models.DateField(null=True)),
                ('hightemp2', models.FloatField(null=True)),
                ('lowtemp2', models.FloatField(null=True)),
                ('date3', models.DateField(null=True)),
                ('hightemp3', models.FloatField(null=True)),
                ('lowtemp3', models.FloatField(null=True)),
                ('date4', models.DateField(null=True)),
                ('hightemp4', models.FloatField(null=True)),
                ('lowtemp4', models.FloatField(null=True)),
                ('date5', models.DateField(null=True)),
                ('hightemp5', models.FloatField(null=True)),
                ('lowtemp5', models.FloatField(null=True)),
                ('date6', models.DateField(null=True)),
                ('hightemp6', models.FloatField(null=True)),
                ('lowtemp6', models.FloatField(null=True)),
                ('date7', models.DateField(null=True)),
                ('hightemp7', models.FloatField(null=True)),
                ('lowtemp7', models.FloatField(null=True)),
                ('date8', models.DateField(null=True)),
                ('hightemp8', models.FloatField(null=True)),
                ('lowtemp8', models.FloatField(null=True)),
                ('date9', models.DateField(null=True)),
                ('hightemp9', models.FloatField(null=True)),
                ('lowtemp9', models.FloatField(null=True)),
                ('date10', models.DateField(null=True)),
                ('hightemp10', models.FloatField(null=True)),
                ('lowtemp10', models.FloatField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
